// YOUTUBE NICHE OPTIONS FOR YOUTUBE VIDEO GEN
export const YOUTUBENICHE = [
  { id: 23, nicheName: "Custom" },
  { id: 1, nicheName: "Tech and Gadgets" },
  { id: 2, nicheName: "Gaming" },
  { id: 3, nicheName: "Personal Development" },
  { id: 4, nicheName: "Finance and Business" },
  { id: 5, nicheName: "Fitness and Health" },
  { id: 6, nicheName: "Food and Cooking" },
  { id: 7, nicheName: "Travel and Adventure" },
  { id: 8, nicheName: "Education and Learning" },
  { id: 9, nicheName: "Beauty and Fashion" },
  { id: 10, nicheName: "Entertainment and Pop Culture" },
  { id: 11, nicheName: "DIY and Home Improvement" },
  { id: 12, nicheName: "Lifestyle" },
  { id: 13, nicheName: "Science and Facts" },
  { id: 14, nicheName: "Cars and Automobiles" },
  { id: 15, nicheName: "Pet and Animal Content" },
  { id: 16, nicheName: "Art and Creativity" },
  { id: 17, nicheName: "Music and Audio" },
  { id: 18, nicheName: "Spirituality and Philosophy" },
  { id: 19, nicheName: "Storytelling" },
  { id: 20, nicheName: "Fun and Challenges" },
  { id: 21, nicheName: "AI and Technology Trends" },
  { id: 22, nicheName: "Digital Marketing" },
];
